name: ğŸ§‘â€ğŸ”§ Test

on:
  push:
    branches:
      - new-dawn
  pull_request:

jobs:
  test-unit:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node & Install dependencies
        uses: ./.github/actions/setup

      - name: Build project
        run: pnpm run build

      - name: Run tests
        run: pnpm run test

  test-e2e:
    name: Run E2E tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node & Install dependencies
        uses: ./.github/actions/setup

      # For now, we only need Chromium.
      - name: Install browsers for Playwright
        run: pnpm dlx playwright install chromium

      - name: Build project
        run: pnpm run build

      - name: Run E2E tests (headless)
        run: pnpm run test:e2e:headless

      - name: Archive Playwright traces
        uses: actions/upload-artifact@v3
        if: success() || failure()
        with:
          name: playwright-traces
          path: |
            wallets/metamask/test-results
          if-no-files-found: error
